//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ActivoMetadata))]
    public partial class Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activo()
        {
            this.HistoricoDepreciacion = new HashSet<HistoricoDepreciacion>();
        }
    
        public int IdActivo { get; set; }
        public int IdUsuario { get; set; }
        public int IdVendedor { get; set; }
        public int IdCategoriaActivo { get; set; }
        public int IdAseguradora { get; set; }
        public int IdMarca { get; set; }
        public string NumeroSerie { get; set; }
        public string Modelo { get; set; }
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public decimal ValorActual { get; set; }
        public decimal CostoColones { get; set; }
        public decimal CostoDolares { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime VencimientoGarantia { get; set; }
        public System.DateTime VencimientoSeguro { get; set; }
        public byte[] imgActivo { get; set; }
        public byte[] imgFactura { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual CategoriaActivo CategoriaActivo { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoDepreciacion> HistoricoDepreciacion { get; set; }
    }
}
