//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(HistoricoDepreciacionMetadata))]
    public partial class HistoricoDepreciacion
    {
        public int Consecutivo { get; set; }
        public int IdActivo { get; set; }
        public decimal Depreciacion { get; set; }
        public System.DateTime FechaDepreciacion { get; set; }
    
        public virtual Activo Activo { get; set; }
    }
}
